<div class="customer-service-dropdown">
    <div class="service-title"><?= __("We're here to help") ?></div>
    <div class="service-contacts">
        <span><?= __('844-532-JMCL (5625)') ?></span>
        <span><?= __('M-F, 9:30am - 5:30pm EST') ?></span>
    </div>
    <ul>
        <li><a href="#"><?= __('Email Us') ?></a></li>
        <li><a href="#"><?= __('Contact Us') ?></a></li>
        <li><a href="#"><?= __('Track Your Order') ?></a></li>
        <li><a href="#"><?= __('Return Policy') ?></a></li>
        <li><a href="#"><?= __('Sign up for Email') ?></a></li>
        <li><a href="#"><?= __('FAQ') ?></a></li>
    </ul>
</div>
