<span class="new-menu-action"><span></span></span>
<div data-mage-init='{"js/newMenu": {}}' class="menu">
    <ul class="submenu">
        <li><a href="http://mag.loc/women.html"><span> <?= __('Women') ?> </span></a>
            <ul class="submenu">
                <li><a href="http://mag.loc/women/tops-women.html"><span><?= __('Tops') ?></a></span>
                    <ul class="submenu">
                        <li><a href="http://mag.loc/women/tops-men/jackets-women.html"><?= __('Jackets') ?></a></li>
                        <li><a href="http://mag.loc/women/tops-men/tees-women.html"><?= __('Tees') ?></a></li>
                    </ul>
                </li>
                <li><a href="http://mag.loc/women/bottoms-women.html"><?= __('Bottoms') ?></a></li>
            </ul>
        </li>
        <li><a href="http://mag.loc/men"><span><?= __('Men') ?></a></span>
            <ul class="submenu">
                <li><a href="http://mag.loc/men/tops-men.html"><?= __('Tops') ?></a></li>
                <li><a href="http://mag.loc/men/bottoms-men.html"><?= __('Bottoms') ?></a></li>
            </ul>
        </li>
        <li><a href="http://mag.loc/training.html"><span><?= __('Training') ?></a></span>
            <ul class="submenu">
                <li><a href="http://mag.loc/training/training-video.html"><?= __('Video Download') ?></a></li>
            </ul>
        </li>
    </ul>
</div>
